#+title: Modules: code

* Table of Contents :TOC:
- [[#info][Info]]
- [[#neko-codeel][neko-code.el]]
- [[#neko-code-lsp-modeel][neko-code-lsp-mode.el]]
- [[#neko-code-eglotel][neko-code-eglot.el]]

* Info

* neko-code.el

This module configures miscellaneous sane defaults related to programming.

- compile :: a built-in package for compilation facilities.
  * set sane defaults.
- elec-pair :: a built-in package for automatic parenthesis pairing.
  * tweak: disable auto-pairing "<" for all org-mode buffers (fixes an issue with org-tempo).
  * enable globally.
- flycheck :: improved syntax checker (better version of flymake (built-in)).
  https://github.com/flycheck/flycheck
  * defer loading.

#+begin_src emacs-lisp :tangle neko-code.el

  (use-package-local compile
    :custom
    (compilation-scroll-output t))

  (use-package-local elec-pair
    :config
    ;; disable "<" pair expansion
    (add-hook 'org-mode-hook
              (lambda ()
                (setq-local electric-pair-inhibit-predicate
                            `(lambda (c)
                               (if (char-equal c ?<)
                                   t
                                 (,electric-pair-inhibit-predicate c))))))
    ;; global
    (electric-pair-mode 1))

  (use-package flycheck
    :defer t)

  
  (provide 'neko-code)

#+end_src

* neko-code-lsp-mode.el

This module installs and sets sane defaults for lsp-mode, providing an IDE-like experience through LSP support and integration with complementary packages.
For more info:
https://emacs-lsp.github.io/lsp-mode/

- lsp-mode :: LSP support for Emacs.
  * defer loading.
    * load package when either the =lsp= or =lsp-deferred= commands are run (set up autoloads for those two commands).
  * bind =C-c l= and =leader l= to the lsp-command-map (run lsp commands from there).
  * hook enabling which-key integration onto lsp-mode.
- corfu integration ::
  * TODO: relocate!

#+begin_src emacs-lisp :tangle neko-code-lsp-mode.el

  (use-package lsp-mode
    ;; defer
    :defer t
    :commands (lsp lsp-deferred)
    ;; bind "C-c l" to lsp-command-map
    :custom (lsp-keymap-prefix "C-c l")
    :general-config
    (neko/leader-definer
      "l" lsp-command-map)
    ;; lsp-command-map which-key integration
    :hook (lsp-mode . lsp-enable-which-key-integration))

  ;; TODO: move this to corfu ?
  ;; if corfu is installed
  ;; (https://github.com/minad/corfu/wiki#configuring-corfu-for-lsp-mode)
  (use-package lsp-mode
    :defer t
    :after corfu
    :hook (lsp-completion-mode . my/lsp-mode-setup-completion)
    :init
    (defvar my/lsp-mode-setup-completion-type '(flex))
    (with-eval-after-load 'orderless
      (setq my/lsp-mode-setup-completion-type '(orderless)))
    (defun my/lsp-mode-setup-completion ()
      (setf (alist-get 'styles (alist-get 'lsp-capf completion-category-defaults))
            my/lsp-mode-setup-completion-type))
    :custom (lsp-completion-provider :none))

  
  (provide 'neko-code-lsp-mode)

#+end_src

* TODO neko-code-eglot.el

#+begin_src emacs-lisp :tangle neko-code-eglot.el

  (use-package eglot
    :defer t)

  
  (provide 'neko-code-eglot)

#+end_src
