#+title: neko-emacs

* Why another emacs distribution?

Besides creating a very nice personal configuration, I found myself frustrated with all the Emacs distributions out there that I've tried. Most of them have a very thick layer of abstraction over vanilla Emacs, which makes both debugging and understanding Emacs on a deeper level much harder to do. I also wanted an ideal Emacs distribution I could point to for friends wanting to try out Emacs---especially a distribution I understand every nook and cranny of. Which led me to turn my personal configuration into this Emacs distro.

* Philosophy

Aims for this Emacs distro:
- Modular
- Simple
- Hackable
- Creates as little of a layer of abstraction over vanilla Emacs as possible
- "Just-works" out of the box, but can be easily modified
- Keep startup time relatively fast

The pathway for most Emacs users (including myself) is starting off with a very "just-works" distro, then switching over to something more minimal, or vanilla Emacs entirely. I wanted to ease this transition as much as possible by making everything as modular and easily hackable as possible, allowing the user to get as close to vanilla Emacs as necessary while staying on this distribution. Think of it as something similar to a pre-made NixOS configuration, where you can easily blacklist, replace, or write and add your own modules to the config, making it so you can slowly tweak it into your own.

* Installation

#+begin_src shell
[ -d "$HOME/.emacs.d" ] && mv ~/.emacs.d ~/.emacs.d.old
git clone https://github.com/lispcat/nekomimi.git ~/.emacs.d
emacs
#+end_src

* Documentation

There is extensive documentation on each module in the following file:
- [[file:modules/Modules.org][Modules.org]]

* Technical overview

- [[file:early-init.el][early-init.el]] :: should not be edited, initializes variables.
  - [[file:personal/early-config.el][personal/early-config.el]] :: to be edited, to overwrite settings in early-init.el.
- [[file:init.el][init.el]] :: should not be edited, loads init files and user-side files
  - [[file:init][init/*]] :: loaded by init.el, necessary or highly recommended to be loaded.
  - [[file:personal/main.el][personal/main.el]] :: loaded by init.el, the main user-side configuration file.

- [[file:modules/neko-modules.el][modules/neko-modules.el]] :: contains a list of functions that provide each "module" to be loaded from personal/main.el.
